### PR TITLE
runme: push Docker image into 'osrf' namespace.

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

### CODE REVIEW

**Comment by tfoote** [comment]
I don't want to confuse this with something that can be found on dockerhub under the osrf organization. It could lead to two accidents, one is people trying to pull it. But worse would be someone trying to push it up accidentially who had permissions then the people trying to pull it might accidentially get something.

A longer name does make sense, at some level it would be better to parameterize the name based on the base architecture.

**Comment by tfoote** [comment]
That sounds good.

**Comment by gavanderhoorn** [comment]
There you go.

**Comment by gavanderhoorn** [comment]
Thanks.

**Pull request merged**
